# Configuration file for the Attestation Server REST API

# Port on which to run the attestation server (default: 8520)
DEFAULTPORT = 8521
# Host on which to listen for the attestation server (default: 0.0.0.0)
DEFAULTHOST = "0.0.0.0"
# Debug mode for the flask app used for development to see errors and stack traces (default: True)
FLASKDEBUG = True
# Run in threaded mode to respond to more than one request at once (default: True)
FLASKTHREADED = True