# Copyright 2021 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

FROM python:3.8-slim

WORKDIR /enrollerclient

RUN apt-get update && apt-get install --yes tpm2-tools

#RUN pip3 install -r requirements.txt
 
ADD constructTPM2JSONobject.py .
ADD enrol.py .
ADD provision .

# Disable the creation of Python bytecode creation and the creations of `__pycache__` directories
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8521

CMD [ "provision"]
