#!/bin/sh
#Copyright 2021 Nokia
#Licensed under the BSD 3-Clause Clear License.
#SPDX-License-Identifier: BSD-3-Clear
#



#
# TPM Stuff
#

EKHANDLE=0x810100ee
AKHANDLE=0x810100aa
ENROLLMENT="http://192.168.1.82:8521"


echo "Removing any existing keys from $EKHANDLE and $AKHANDLE"
tpm2_evictcontrol -Q -c $EKHANDLE
tpm2_evictcontrol -Q -c $AKHANDLE
echo "Clearing temporary objects from TPM"
tpm2_flushcontext -Q -t
tpm2_flushcontext -Q -s
tpm2_flushcontext -Q -l

echo "Persistent handles - should be empty:"
tpm2_getcap handles-persistent
echo "Transient handles - should be empty:"
tpm2_getcap handles-transient
echo "Session handles - should be empty:"
tpm2_getcap handles-loaded-session


echo "Generating temporary directory"
TMPDIR=/tmp/
mydir=$(mktemp -d "${TMPDIR:-$mydir/}$(basename $0).XXXXXXXXXXXX")
echo $mydir

echo "Generating EK"
tpm2_createek -Q -c $EKHANDLE -G rsa

echo "Generating AK"
tpm2_createak -Q -C $EKHANDLE -c $mydir/ak.ctx -G rsa -g sha256 -s rsassa -u $mydir/ak.pub 
tpm2_evictcontrol -Q -c $mydir/ak.ctx $AKHANDLE

echo "Generating PEM and data files"
#NB: these must not be "quiet -Q otherwise there's no output"
#tpm2_readpublic -c $EKHANDLE > $mydir/ek.yaml 
#tpm2_readpublic -c $AKHANDLE > $mydir/ak.yaml 
#These can be quiet because there's an explicit output file
tpm2_readpublic -Q -c $EKHANDLE -o $mydir/ek.pem -f pem 
tpm2_readpublic -Q -c $AKHANDLE -o $mydir/ak.pem -f pem 

echo "Listing temporary files in " $mydir
ls -l $mydir 

echo "Clearing temporary objects from TPM"
tpm2_flushcontext -Q -t
tpm2_flushcontext -Q -s
tpm2_flushcontext -Q -l

echo "Persistent handles - should contain AK and EK:"
tpm2_getcap handles-persistent
echo "Transient handles - should be empty:"
tpm2_getcap handles-transient
echo "Session handles - should (might) be empty:"
tpm2_getcap handles-loaded-session



#
#Enrollment
#
echo "\nSetting up the basic element identification details"

python3 enrol.py $ENROLLMENT enrol.json

echo "Done."