#!/bin/sh
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
sudo pip3 uninstall a10structures
sudo rm -rf a10server.egg-info build dist
sudo python3 setup.py sdist bdist_wheel
sudo python3 setup.py install
